### ISSUE TITLE
It opens Kotlin/Java files before creating them

### ISSUE THREAD

**Issue by JulienCros** [mateusz1913/vision-camera-plugin-builder#18]
### Environment

node version: v16.15.0

Ubuntu 22.04
Virtualbox VM

### Is used with npx or as a local dependency?

- [X] npx
- [ ] local dependency

### Affected commands

- [X] android
- [ ] ios

### Current behavior

![image](https://user-images.githubusercontent.com/44341623/177827618-910b6d06-eab1-4727-8e83-c262496b48eb.png)

It tries to write into the file but it didn't first created them.

### Expected behavior

It should be creating it before writing content inside and thus not throwing any error.

### Reproduction repository link

https://github.com/JulienCros/error_plugin_builder

**Comment by mateusz1913** [comment]
👋 @JulienCros your reproduction repo android project does not have any java/kotlin source set (only resources). The CLI _assumes_ that it will create files in _valid_ React Native android project - the one that has valid java/kotlin source set with folder structure matching project's package name - in your case it should have `java/com/example/imageprocessing` folder structure inside `android/app/src/main`.

I don't think, it's CLI responsibility to create whole java/kotlin source set as in 99% cases, it should already be there.

Try to add `java/com/example/imageprocessing` to your reproduction repo (you can try adding MainActivity.java|kt inside that source set) and retry the CLI

**Comment by JulienCros** [comment]
I believe git didn't pushed it because it was empty but it was there on my computer, I tried without and it gives another error. So I don't think it is the problem... Thx for helping me
