### ISSUE TITLE
Error building android plugin

### ISSUE THREAD

**Issue by Lucianofc138** [mateusz1913/vision-camera-plugin-builder#19]
### Environment

node version: v16.8.0

### Is used with npx or as a local dependency?

- [X] npx
- [ ] local dependency

### Affected commands

- [X] android
- [ ] ios

### Current behavior

![image](https://user-images.githubusercontent.com/55565367/178807171-11e8554c-b387-4b2a-8678-59e62c343d28.png)

As shown in the image above, the file for the Plugin nor the Package cannot be opened since the directory doesn't exist. Checking the android directory I realized the the directory was created, but the name was written lower case (`.../android/app/src/main/java/com/rncamera0/xyzframeprocessor` instead of `.../android/app/src/main/java/com/rncamera0/XyzFrameProcessor`).

Considering the previous, it works well when using a name with only lowercase characters, for instance: `xyzframeprocessor`.

Also I think the problem is here in the file `https://github.com/mateusz1913/vision-camera-plugin-builder/blob/main/src/android.ts`, specifically in the lines 221, where the folder is created with the pluginName in lowercase, and 230, where pluginName is used as the name for the folder without using the method toLowerCase on it (shown below).

![image](https://user-images.githubusercontent.com/55565367/178811390-e83a91b1-3634-49fa-b4bc-29b6158423ed.png)

*I would love to fix it myself, but I'm not quite sure how to test the command once I clone and edit it, I've only use it through npx so far.

### Expected behavior

I would expect the command to work following the convention in the example in the docs of react-native-vision-camera (QRCodeFrameProcessor), or in the example in the wizard of the command (XyzFrameProcessor), which is PascalCase.

### Reproduction repository link

https://github.com/Lucianofc138/vcpb-issue-reproduction-0

**Comment by mateusz1913** [comment]
Hey @Lucianofc138, thx for that detailed report 🚀 

If you would like to make a PR and run cli locally, you can just clone the repo and build it with `yarn build` - it will produce build folder with `index.js` inside. Then you can just type `node <path-to-cloned-repo-build-index-js-file> android` from your library/app directory and it will use your locally built cli

If you'll have any problems, feel free to ask. And if you'll not able to make a PR, I will try to fix later this week

**Comment by Lucianofc138** [comment]
(I miss clicked and close the issue. My bad. )
I made a PR with the changes needed to fix the issue. I tried them and it worked for me. I hope it doesn't break anything.

**Comment by mateusz1913** [comment]
@Lucianofc138 thx for your contribution! Your fix is available in v0.1.1 🚀  - if you use cli with `npx`, you might have old version cached. Try to `npx vision-camera-plugin-builder@latest <command>`, if it won't update to 0.1.1, try to clear npx cache (npm config get cache will ist directories with cached libraries - try to find one for cli and remove it)
