### ISSUE TITLE
Few updates

### ISSUE THREAD

**Issue by mrousavy** [mateusz1913/vision-camera-plugin-builder#41]
### Feature request

Hey man! Love your CLI.

There's gonna be a small change in V3 which registers plugins differently, instead of using `createNativeModules` we will now use the constructor/`init` call. Can you update the template for that?

Feel free to join the Margelo community discord if you want to discuss this further.

Also, do you upgrade the template to the most recent Native Module template always?

**Comment by mrousavy** [comment]
Actually I think we should re-structure the docs.

The native FP guide should be 1. create a FP plugin in your codebase, then 2. ship it to npm using either the manual setup or your CLI.

**Comment by mateusz1913** [comment]
Hi! Point me to the PR that refactors `createNativeModules` to `init`, so that I can see and compare the changes needed to be done and I'll try to update it asap.

Regarding the native module template, no, I update it only, if Vision Camera docs for manual FP creation change

**Comment by mrousavy** [comment]
Hey! sorry for the late reply, but new docs are live! https://react-native-vision-camera.com > under create native modules (android). It's no longer in the getNativeModules func

**Comment by mateusz1913** [comment]
It's done with v0.4.0 🚀

**Comment by mrousavy** [comment]
awesome work man!
