### ISSUE TITLE
Missing Constructor in Plugin Java Class

### ISSUE THREAD

**Issue by LordXerus** [mateusz1913/vision-camera-plugin-builder#61]
### Environment

node version: 20.0.10

### Is used with npx or as a local dependency?

- [X] npx
- [ ] local dependency

### Affected commands

- [X] android
- [ ] ios

### Current behavior

`npx expo run:android` fails to build with java build errors looking like this
```
receipt-scanner-rush/android/app/src/main/java/com/lordxerus/receiptscannerrush/receiptocrframeprocessorplugin/ReceiptOCRFrameProcessorPluginPluginPackage.java:19: error: constructor ReceiptOCRFrameProcessorPluginPlugin in class ReceiptOCRFrameProcessorPluginPlugin cannot be applied to given types;
            options -> new ReceiptOCRFrameProcessorPluginPlugin(options)
                       ^
  required: no arguments
  found:    Map<String,Object>
  reason: actual and formal argument lists differ in length
receipt-scanner-rush/android/app/src/main/java/com/lordxerus/receiptscannerrush/receiptocrframeprocessorplugin/ReceiptOCRFrameProcessorPluginPlugin.java:9: error: constructor FrameProcessorPlugin in class FrameProcessorPlugin cannot be applied to given types;
public class ReceiptOCRFrameProcessorPluginPlugin extends FrameProcessorPlugin {
       ^
  required: Map<String,Object>
  found:    no arguments
  reason: actual and formal argument lists differ in length
```
**Actual and formal argument lists differ in length**
_pls ignore my interesting names im new to dis_

I believe this is because the default code in `android-utils.ts` does not generate a constructor
As a result, Java generates a default constructor with no parameters and calls the super constructor with no arguments
Which I believe causes the errors above.

Reproduction Instructions:
1. Create Java Plugin
2. No Constructor is generated
3. Gradle build does not error

I'm fairly sure my conclusion is correct so I will provide a reproduction repository upon request.

### Expected behavior

`npx expo run:android` builds successfully

My solution to the above errors is to add a dummy constructor, maybe with comments

```java
ReceiptOCRFrameProcessorPluginPlugin(@Nullable Map<String, Object> options) {
    super(options);
    Log.d("ExamplePlugin", "ExampleFrameProcessorPlugin initialized with options: " + options);
  }
```

### Reproduction repository link

Reproduction repository upon request; see Current Behavior for repro

**Comment by mateusz1913** [comment]
Hey @LordXerus thx for reporting the issue. It's fixed in release 0.6.0 🎉
